#!/bin/bash
# Script that written to protect Linux Servers/PCs and routers.

# You can use some tweaks on upstream linux hardware.
# But, in this case, you need to replace INPUT -> FORWARD.
# It will give better protection to connected machines.

# Use with Fail2ban & Any IPS for best results.
# Enjoy! Made by yuki with love <3.

# --------------------------------
# ToDo:
# Maybe block echo requests
# DROP Policy by default (for INPUT) + logging
# Better customization
# Optimization
# Better IPv6 Protection
# Block incorrect sequence numbers
# Multiport for webserver and SSH
# Iplist in the file
# Automatic update by cron
# Move fully to nftables
# Tarpit + notrack for TPBA variable
# Auto-Backup of an netfilter rules
# Restrict length of some ICMP types
# Block invalid packets
# Add built-in guide how to capture attacks
# AMP Autoblock
# --------------------------------

# Configuration
# ------------------------

# ipt-nft, ip6t-nft, ipset
IP="/sbin/iptables-nft"
IP6="/sbin/ip6tables-nft"
IPS="/sbin/ipset"

# SSH Port
# For example: 2222
# You dont have SSH?
# Then dont touch this
# Default: 22 (ssh)
SSH="22"

# Port of your webserver
# For example: 8080
# You dont have webserver?
# Then dont touch this
# Default: 80 (http)
HTTP="80"

# Enable SYN Proxy for some ports
# To mitigate powerful SYN Floods
SYNPROXY="22,80,443"

# Connection limit (per one IP)
# Recommended: 100
# If you server has only SSH,
# And you are under TCP DDoS,
# You can set here value ~50
CL="100"

# Connection limit action
# Recommended: REJECT
# Under DDoS you can set DROP here
# To reduce the load on the CPU
CLA="REJECT --reject-with tcp-reset"

# Useragent block action
# Recommended: REJECT
# You should use WAF if you're under attack
# Or if you're using HTTPS+HSTS
UBA="REJECT --reject-with tcp-reset"

# Proto block action
# Recommended: ICMP proto unreach message
# Under DDoS (Layer3) you can try to change it
# To DROP, it will reduce CPU Load
PBA="REJECT --reject-with icmp-proto-unreach"

# IP Block action
# Recommended: DROP
# No need to change it without reason.
IBA="DROP"

# TCP Port Block action
# Recommended: DROP
TPBA="DROP"

# UDP Port Block action
# Recommended: DROP
UPBA="DROP"

# TCP SYN PPS limit (per IP)
# Recommended: 4/s
SPL="4/s"

# UDP PPS limit (per IP)
# May cause problems.
# If your server under this type of DDoS,
# Try to set 300 here for short time.
# Recommended: 700
UPL="700"

# UDP to SSH Block action
# Recommended: DROP
USBA="DROP"

# +++++++

# Color
LightBlue='\033[1;36m'

# --------------------------------

# Return error if the script isn't started as root.

if [ "$(whoami)" != "root" ]; then
         echo -e "${LightBlue}[!] Run this script as root"
        exit 255
fi

# --------------------------------

# Create backup of the sysctl.conf. Exists? Will be overwritten.
cp /etc/sysctl.conf{,.backup}

# Flush chain "filter" to prevent some problems.
nft flush chain inet filter input
clear

# Delete "blacklist" ip set.
"$IPS" destroy blacklist

# --------------------------------
# Rules...

# Don't limit "lo" iface.
# --------------------------------
 "$IP" -I INPUT -i lo -j ACCEPT
 "$IP" -I OUTPUT -o lo -j ACCEPT

# Limit SYN PPS to mitigate SYN Floods.
# --------------------------------
 "$IP" -t raw -I PREROUTING -p tcp --syn --match hashlimit --hashlimit-above "$SPL" --hashlimit-mode srcip --hashlimit-name synflood -j DROP

# Limit UDP PPS to mitigate UDP Floods.
# --------------------------------
 "$IP" -t raw -I PREROUTING -p udp -m limit --limit "$UPL"/s -j ACCEPT
 "$IP" -t raw -A PREROUTING -p udp -j DROP

# Limit outgoing ICMP "Port Unreach" PPS to offload server in the case of UDP Flood.
# --------------------------------
 "$IP" -t raw -A OUTPUT -p icmp --icmp-type port-unreach -m limit --limit 6/m --limit-burst 2 -j ACCEPT
 "$IP" -t raw -A OUTPUT -p icmp --icmp-type port-unreach -j DROP

# Block some types of ICMP and limit all other types.
# ----------------------------------------------------------------
 "$IP" -t raw -I PREROUTING -p icmp --icmp-type address-mask-request -j DROP
 "$IP" -t raw -I PREROUTING -p icmp --icmp-type router-solicitation -j DROP
 "$IP" -t raw -I PREROUTING -p icmp --icmp-type timestamp-request -j DROP
 "$IP" -t raw -A PREROUTING -p icmp -m limit --limit 2/s -j ACCEPT
 "$IP" -t raw -A PREROUTING -p icmp -j DROP

# Block TCP packets with wrong flags to increase security and block simple attacks.
# ----------------------------------------------------------------
 "$IP" -t raw -A PREROUTING -p tcp --tcp-flags ALL SYN,RST,ACK,FIN,URG -j DROP
 "$IP" -t raw -A PREROUTING -p tcp --tcp-flags ALL SYN,FIN,PSH,URG -j DROP
 "$IP" -t raw -A PREROUTING -p tcp --tcp-flags ALL FIN,PSH,URG -j DROP
 "$IP" -t raw -A PREROUTING -p tcp --tcp-flags FIN,RST FIN,RST -j DROP
 "$IP" -t raw -A PREROUTING -p tcp --tcp-flags SYN,FIN SYN,FIN -j DROP
 "$IP" -t raw -A PREROUTING -p tcp --tcp-flags SYN,RST SYN,RST -j DROP
 "$IP" -t raw -A PREROUTING -p tcp --tcp-flags FIN,SYN FIN,SYN -j DROP
 "$IP" -t raw -A PREROUTING -p tcp --tcp-flags FIN,ACK FIN -j DROP
 "$IP" -t raw -A PREROUTING -p tcp --tcp-flags ACK,URG URG -j DROP
 "$IP" -t raw -A PREROUTING -p tcp --tcp-flags ACK,FIN FIN -j DROP
 "$IP" -t raw -A PREROUTING -p tcp --tcp-flags ACK,PSH PSH -j DROP
 "$IP" -t raw -A PREROUTING -p tcp --tcp-flags ALL NONE -j DROP
 "$IP" -t raw -A PREROUTING -p tcp --tcp-flags ALL ALL -j DROP

# Block unsafe ports to increase security.
# ----------------------------------------------------------------
 "$IP" -t raw -I PREROUTING -p UDP -m multiport --dports 7,19,25,135,136,137,138,139,445,1900,3389 -j "$UPBA"
 "$IP" -t raw -I PREROUTING -p TCP -m multiport --dports 7,19,25,135,136,137,138,139,445,1900,3389 -j "$TPBA"

# Block LAND attack.
# --------------------------------
 "$IP" -t raw -I PREROUTING -s 127.0.0.0/8 ! -i lo -j DROP

# Limit DNS/NTP PPS to offload CPU under AMP DDoS with these protocols.
# Also, block packets with specified s-ports to reduce CPU load caused by simple attacks.
# --------------------------------
 "$IP" -t raw -A PREROUTING -p udp --sport 123 -m limit --limit 2/s --limit-burst 1 -j ACCEPT
 "$IP" -t raw -A PREROUTING -p udp --sport 53 -m limit --limit 4/s --limit-burst 10 -j ACCEPT
 "$IP" -t raw -A PREROUTING -p udp -m multiport --sports 53,123,17185,7001,9000 -j DROP

# Block invalid length of TCP/UDP packets to mitigate some attacks.
# --------------------------------
 "$IP" -t raw -I PREROUTING -p tcp -m length --length 0 -j DROP
 "$IP" -t raw -I PREROUTING -p udp -m length --length 0:8 -j DROP

# Limit connections per IP to mitigate impact from HANDSHAKE and Slowloris.
# --------------------------------
 "$IP" -t mangle -I PREROUTING -p tcp -m connlimit --connlimit-above "$CL" -j "$CLA"

# Limit TCP FIN/RST PPS to mitigate some attacks.
# --------------------------------
 "$IP" -t raw -A PREROUTING -p tcp --tcp-flags RST RST -m limit --limit 2/s --limit-burst 2 -j ACCEPT
 "$IP" -t raw -A PREROUTING -p tcp --tcp-flags FIN FIN -m limit --limit 2/s --limit-burst 2 -j ACCEPT
 "$IP" -t raw -A PREROUTING -p tcp --tcp-flags RST RST -j DROP
 "$IP" -t raw -A PREROUTING -p tcp --tcp-flags FIN FIN -j DROP

# Protect SSH against very quick connection establishing.
# --------------------------------
 "$IP" -t mangle -I PREROUTING -p tcp --dport "$SSH" -m state --state NEW -m recent --set
 "$IP" -t mangle -I PREROUTING -p tcp --dport "$SSH" -m state --state NEW -m recent --update --seconds 60 --hitcount 16 -j DROP

# Reject UDPs to SSH port to prevent UDP attacks on the SSH.
# --------------------------------
 "$IP" -t raw -A PREROUTING -p udp --dport "$SSH" -j "$USBA"

# Redirect suspicious packets to SYNPROXY.
# Mitigates SYN Floods and some sophiscated TCP attacks.
# --------------------------------
 "$IP" -I INPUT -p tcp -m multiport --dports "$SYNPROXY" -m conntrack --ctstate INVALID,UNTRACKED -j SYNPROXY --timestamp --sack-perm

# Drop UDP/TCP packets with invalid s-ports to prevent some attacks.
# --------------------------------
 "$IP" -t raw -I PREROUTING -p udp ! --sport 1:65535 -j DROP
 "$IP" -t raw -I PREROUTING -p tcp ! --sport 1:65535 -j DROP

# Drop fragmented packets to prevent some attacks.
# --------------------------------
 "$IP" -t raw -I PREROUTING -f -j DROP

# Drop new TCP packets that arent SYNs to prevent popular TCP attacks.
# --------------------------------
 "$IP" -t mangle -I PREROUTING -p tcp ! --syn -m conntrack --ctstate NEW -j DROP
 "$IP" -t raw -I PREROUTING -p tcp --tcp-flags ACK,FIN FIN -j DROP

# Drop TCPs with invalid MSS to mitigate some attack types.
# I recommend you to set own max mss value if you know it.
# If you have determined that this causes problems, try to increase it to 65535.
# --------------------------------
 "$IP" -t mangle -I PREROUTING -p tcp -m conntrack --ctstate NEW -m tcpmss ! --mss 536:10000 -j DROP

# Drop SYNs with s-port >1024 to prevent many attack types.
# --------------------------------
 "$IP" -t raw -I PREROUTING -p tcp --syn ! --sport 1024:65535 -j DROP

# Don't allow HTTP Requests with suspicious useragents to increase security.
# --------------------------------
 "$IP" -A INPUT -p tcp --dport "$HTTP" -m string --string 'WordPress' --algo kmp -j "$UBA"
 "$IP" -A INPUT -p tcp --dport "$HTTP" -m string --string 'stresser' --algo kmp -j "$UBA"
 "$IP" -A INPUT -p tcp --dport "$HTTP" -m string --string 'benchmark' --algo kmp -j "$UBA"
 "$IP" -A INPUT -p tcp --dport "$HTTP" -m string --string 'MD5(' --algo kmp -j "$UBA"
 "$IP" -A INPUT -p tcp --dport "$HTTP" -m string --string 'censys' --algo kmp -j "$UBA"
 "$IP" -A INPUT -p tcp --dport "$HTTP" -m string --string 'inspect' --algo kmp -j "$UBA"
 "$IP" -A INPUT -p tcp --dport "$HTTP" -m string --string 'scaner' --algo kmp -j "$UBA"
 "$IP" -A INPUT -p tcp --dport "$HTTP" -m string --string 'shodan' --algo kmp -j "$UBA"

# Drop popular signature of SNMP-based attacks to mitigate them.
# --------------------------------
 "$IP" -t raw -A PREROUTING -p udp --sport 161 -m length --length 2536 -j DROP
 "$IP" -t raw -A PREROUTING -p udp --sport 161 -m length --length 1244 -j DROP

# Block some Layer3 Protocols to mitigate ESP/GRE/Ah floods.
# If you need these protos - delete rules below.
# --------------------------------
 "$IP" -t raw -A PREROUTING -p esp -j "$PBA"
 "$IP" -t raw -A PREROUTING -p gre -j "$PBA"
 "$IP" -t raw -A PREROUTING -p ah -j "$PBA"

# Drop all broadcasted packets to block fraggle/smurf attacks.
# --------------------------------
 "$IP" -t raw -I PREROUTING -m pkttype --pkt-type broadcast -j DROP

# Drop IPv4 packets with SSR option to block some spoof types.
# --------------------------------
 "$IP" -t raw -A PREROUTING -m ipv4options --ssrr -j DROP

# Limit SYN/ICMPv6 PPS to mitigate some IPv6 attacks.
# They're not currently not popular.
# ----------------------------------------------------------------
 "$IP6" -t raw -A PREROUTING -p icmpv6 -m limit --limit 4/s -j ACCEPT
 "$IP6" -t raw -A PREROUTING -p icmpv6 -j DROP
 "$IP6" -t raw -A PREROUTING -p tcp --syn -m limit --limit 3/s --limit-burst 10 -j ACCEPT
 "$IP6" -t raw -A PREROUTING -p tcp --syn -j DROP

# Block some multicast IPs, censys IPs, shodan IPs...
# We use big hashsize, so it doesn't affects performance.
# --------------------------------
 "$IPS" create blacklist nethash hashsize 260000
 "$IPS" add blacklist 240.0.0.0/5
 "$IPS" add blacklist 162.142.125.0/24
 "$IPS" add blacklist 167.94.138.0/24
 "$IPS" add blacklist 198.20.69.0/24
 "$IPS" add blacklist 198.20.70.114
 "$IPS" add blacklist 93.120.27.62
 "$IPS" add blacklist 66.240.236.119
 "$IPS" add blacklist 66.240.205.34
 "$IPS" add blacklist 198.20.99.130
 "$IPS" add blacklist 71.6.135.131
 "$IPS" add blacklist 66.240.192.138
 "$IPS" add blacklist 71.6.167.142
 "$IPS" add blacklist 82.221.105.0/24
 "$IPS" add blacklist 71.6.165.200
 "$IPS" add blacklist 188.138.9.50
 "$IPS" add blacklist 85.25.103.50
 "$IPS" add blacklist 85.25.43.94
 "$IPS" add blacklist 71.6.146.185
 "$IPS" add blacklist 71.6.158.166
 "$IPS" add blacklist 198.20.87.98
 "$IPS" add blacklist 185.163.109.66
 "$IPS" add blacklist 94.102.49.0/24
 "$IPS" add blacklist 104.131.0.69
 "$IPS" add blacklist 104.236.198.48
 "$IPS" add blacklist 155.94.222.0/24
 "$IPS" add blacklist 155.94.254.0/24
 "$IPS" add blacklist 162.142.125.0/24
 "$IPS" add blacklist 167.94.138.0/24
 "$IPS" add blacklist 167.94.145.0/24
 "$IPS" add blacklist 167.94.146.0/24
 "$IPS" add blacklist 167.248.133.0/24
 "$IPS" add blacklist 2602:80d:1000:b0cc:e::/80
 "$IPS" add blacklist 2620:96:e000:b0cc:e::/80
 "$IP" -t raw -A PREROUTING -m set --match-set blacklist src -j "$IBA"

# Advanced rules
 # Block one of leaked OVH Bypass payload.
 # --------------------------------
  "$IP" -t raw -A PREROUTING -m string --algo bm --string "\x77\x47\x5E\x27\x7A\x4E\x09\xF7\xC7\xC0\xE6" -j DROP

 # Block some exposed payloads.
 # --------------------------------
  "$IP" -t raw -I PREROUTING -p tcp -m length --length 40 -m string --algo bm --string "0xd3da" -m state --state ESTABLISHED -j DROP
  "$IP" -t raw -I PREROUTING -p tcp -m length --length 40 -m string --algo bm --string "0x912e" -m state --state ESTABLISHED -j DROP
  "$IP" -t raw -I PREROUTING -p tcp -m length --length 40 -m string --algo bm --string "0x0c54" -m state --state ESTABLISHED -j DROP
  "$IP" -t raw -I PREROUTING -p tcp -m length --length 40 -m string --algo bm --string "0x38d3" -m state --state ESTABLISHED -j DROP

 # Block signatures of some popular CNC software.
 # --------------------------------
  "$IP" -t raw -A PREROUTING -p udp -m u32 --u32 "2&0xFFFF=0x2:0x0100" -j DROP
  "$IP" -t raw -A PREROUTING -p udp -m u32 --u32 "12&0xFFFFFF00=0xC0A80F00" -j DROP
  "$IP" -t raw -A PREROUTING -p tcp -syn -m length --length 52 u32 --u32 "12&0xFFFFFF00=0xc838" -j DROP
  "$IP" -t raw -A PREROUTING -p udp -m length --length 28 -m string --algo bm --string "0x0010" -j DROP
  "$IP" -t raw -A PREROUTING -p udp -m length --length 28 -m string --algo bm --string "0x0000" -j DROP
  "$IP" -t raw -A PREROUTING -p tcp -m length --length 40 -m string --algo bm --string "0x0020" -j DROP
  "$IP" -t raw -A PREROUTING -p tcp -m length --length 40 -m string --algo bm --string "0x0c54" -j DROP
  "$IP" -t raw -A PREROUTING -p tcp --tcp-flags ACK ACK -m length --length 52 -m string --algo bm --string "0x912e" -m state --state ESTABLISHED -j DROP
  "$IP" -t mangle -A PREROUTING -p tcp -syn -m length --length 52 -m string --algo bm --string "0xc838" -m state --state ESTABLISHED -j DROP

 # Block suspicious strings to mitigate impact of some attacks.
 # --------------------------------
  "$IP" -t raw -A PREROUTING -m string --algo bm --string "CRI" -j DROP
  "$IP" -t raw -A PREROUTING -m string --algo bm --string "STD" -j DROP
  "$IP" -t raw -A PREROUTING -m string --algo bm --string "std" -j DROP
  "$IP" -t raw -A PREROUTING -m string --algo bm --string "ddos" -j DROP
  "$IP" -t raw -A PREROUTING -m string --algo bm --string "flood" -j DROP
  "$IP" -t raw -A PREROUTING -m string --algo bm --string "HACKED" -j DROP

 # Block exposed payloads of NULL method.
 # --------------------------------
  "$IP" -t raw -A PREROUTING -m string --algo bm --string "0x00000" -j DROP
  "$IP" -t raw -A PREROUTING -m string --algo bm --string "0x000000000001" -j DROP

 # Block NTP Reflection packets.
 # --------------------------------
  "$IP" -t raw -A PREROUTING -p udp -m u32 --u32 "0>>22&0x3C@8" -j DROP
  "$IP" -t raw -A PREROUTING -p udp -m u32 --u32 "0>>22&0x3C@8&0xFF=42" -j DROP
  "$IP" -t raw -A PREROUTING -p udp -m u32 --u32 "0>>22&0x3C@8&0xFF" -j DROP

 # Patch SYNOPT-ACK Method.
 # --------------------------------
  "$IP" -t raw -A PREROUTING -p tcp --sport 21 --dport 21 --tcp-flags SYN,ACK SYN,ACK -j DROP

 # Block some exposed bypass payloads.
 # --------------------------------
  "$IP" -t raw -A PREROUTING -p udp -m string --algo bm --hex-string "|424f4f5445524e4554|" -j DROP
  "$IP" -t raw -A PREROUTING -p udp -m string --algo bm --hex-string "|41545441434b|" -j DROP
  "$IP" -t raw -A PREROUTING -p udp -m string --algo bm --hex-string "|504r574552|" -j DROP
  "$IP" -t raw -A PREROUTING -p udp -m string --algo bm --hex-string "|6c6e6f6172656162756e6386f6673b694464696573|" -j DROP
  "$IP" -t raw -A PREROUTING -p udp -m string --algo bm --hex-string "|736b6954|" -j DROP
  "$IP" -t raw -A PREROUTING -p udp -m string --algo bm --hex-string "|736b69646e6574|" -j DROP
  "$IP" -t raw -A PREROUTING -p udp -m multiport --dports 16000:29000,"$SSH" -m string --to 75 --algo bm --string 'HTTP/1.1 200 OK' -j DROP
  "$IP" -t raw -A PREROUTING -p udp --dport 16000:29000 -m string --to 75 --algo bm --string 'HTTP/1.1 200 OK' -j DROP
  "$IP" -t raw -A PREROUTING -p udp -m udp -m string --hex-string "|7374640000000000|" --algo kmp --from 28 --to 29 -j DROP
  "$IP" -t raw -A PREROUTING -p udp -m u32 --u32 "6&0xFF=0,2:5,7:16,18:255" -j DROP
  "$IP" -t raw -A PREROUTING -m u32 --u32 "12&0xFFFF=0xFFFF" -j DROP
  "$IP" -t raw -A PREROUTING -m u32 --u32 "28&0x00000FF0=0xFEDFFFFF" -j DROP
  "$IP" -t raw -A PREROUTING -m string --algo bm --from 28 --to 29 --string "farewell" -j DROP
  "$IP" -t raw -A PREROUTING -p udp -m udp -m string --hex-string "|53414d50|" --algo kmp --from 28 --to 29 -j DROP



# Sysctl.conf tweaks
# --------------------------------

 echo -e "
#
# /etc/sysctl.conf - Configuration file for setting system variables
# See /etc/sysctl.d/ for additional system variables.
# See sysctl.conf (5) for information.
#

#kernel.domainname = example.com

#
# Tweaks by https://github.com/yuk1c/antiddos
#


# Set custom Netfilter CT timeouts.
# --------------------------------
 net.netfilter.nf_conntrack_tcp_timeout_last_ack = 10
 net.netfilter.nf_conntrack_tcp_timeout_close = 5
 net.netfilter.nf_conntrack_tcp_timeout_close_wait = 5
 net.netfilter.nf_conntrack_tcp_timeout_time_wait = 5
 net.netfilter.nf_conntrack_tcp_timeout_syn_sent = 10
 net.netfilter.nf_conntrack_tcp_timeout_syn_recv = 10
 net.netfilter.nf_conntrack_tcp_timeout_fin_wait = 10
 net.netfilter.nf_conntrack_tcp_timeout_unacknowledged = 30
 net.netfilter.nf_conntrack_generic_timeout = 120
 net.netfilter.nf_conntrack_udp_timeout = 10
 net.netfilter.nf_conntrack_icmp_timeout = 2
 net.netfilter.nf_conntrack_icmpv6_timeout = 3

# Enable SYN-Cookies.
# --------------------------------
 net.ipv4.tcp_syncookies = 1
 # Change value above to 2,
 # If you are under SYN DoS,
 # And if your server is slow.
 # Value '2' means that SYN-Cookies are always enabled.

# Set minimal SYN/SYN-ACK retries count.
# --------------------------------
 net.ipv4.tcp_synack_retries = 1
 net.ipv4.tcp_syn_retries = 1

# Enable RFC 1337.
# --------------------------------
 net.ipv4.tcp_rfc1337 = 1

# Set large NIC buffers.
# --------------------------------
 net.core.rmem_max = 33554432
 net.core.wmem_max = 33554432

# Use TCP MTU Probing when kernel detects ICMP BH.
# --------------------------------
 net.ipv4.tcp_mtu_probing = 1

# Set large route table size (IPv4 & IPv6).
# --------------------------------
 net.ipv6.route.max_size = 2147483647
 net.ipv4.route.max_size = 2147483647

# Network security hardening.
# --------------------------------
 net.ipv4.conf.all.accept_redirects = 0
 net.ipv4.conf.all.secure_redirects = 0
 net.ipv4.conf.all.send_redirects = 0
 net.ipv4.conf.all.accept_source_route = 0
 net.ipv6.conf.all.accept_source_route = 0
 net.ipv6.conf.all.accept_ra = 0
 net.ipv4.conf.all.secure_redirects = 1
 net.ipv6.conf.all.drop_unsolicited_na = 1
 net.ipv6.conf.all.use_tempaddr = 2
 net.ipv4.conf.all.drop_unicast_in_l2_multicast = 1
 net.ipv6.conf.all.drop_unicast_in_l2_multicast = 1
 net.ipv6.conf.default.dad_transmits = 0
 net.ipv6.conf.default.autoconf = 0

# Prevent ARP Spoofing.
# --------------------------------
 net.ipv4.conf.all.drop_gratuitous_arp = 1
 net.ipv4.conf.all.arp_ignore = 1
 net.ipv4.conf.all.arp_filter = 1

# Disable IGMP Multicast reports.
# --------------------------------
 net.ipv4.igmp_link_local_mcast_reports = 0

# Overall security hardening.
# --------------------------------
 kernel.dmesg_restrict = 1
 kernel.kptr_restrict = 1
 kernel.nmi_watchdog = 0
 fs.protected_symlinks = 1
 fs.protected_hardlinks = 1
 fs.protected_fifos = 2
 fs.protected_regular = 2
 kernel.unprivileged_bpf_disabled = 1
 kernel.unprivileged_userns_clone = 0
 kernel.printk = 3 3 3 3
 net.core.bpf_jit_harden = 2
 vm.unprivileged_userfaultfd = 0
 kernel.kexec_load_disabled = 1
 #kernel.sysrq = 0 # Disables sysrq (not recommended)
 #net.ipv4.ip_forward = 0 # Disables ip_forward (may block VPN)

# Performance tuning.
# --------------------------------
 kernel.sched_tunable_scaling = 1
 net.ipv4.tcp_moderate_rcvbuf = 1
 net.ipv4.tcp_slow_start_after_idle = 0
 kernel.shmmax = 268435456
 net.ipv4.tcp_tw_reuse = 1

# Enable ExecShield to block some remote attacks.
# --------------------------------
 kernel.exec-shield = 2

# Ignore ICMP Bogus responses.
# --------------------------------
 net.ipv4.icmp_ignore_bogus_error_responses = 1

# Disable conntrack helper.
# --------------------------------
 net.netfilter.nf_conntrack_helper = 0

# Allow to use more ports as a s-ports.
# --------------------------------
 net.ipv4.ip_local_port_range=1024 65535

# Disable conntrack TCP Loose (we need this to enable SYN Proxy).
# --------------------------------
 net.netfilter.nf_conntrack_tcp_loose = 0

# Reverse-path filter.
# You should set '1' to '0' if you're using an assymetric routing.
# --------------------------------
 net.ipv4.conf.all.rp_filter = 1

# Set big CT table size.
# --------------------------------
 net.netfilter.nf_conntrack_max = 10000000" > /etc/sysctl.conf

sysctl -p
systemctl enable --now netfilter-persistent
clear

echo -e "${LightBlue}"
echo -e "[✓] Script changes applied, but rules aren't saved.
Check the network now, and if it fine - save the rules using 'sudo netfilter-persistent save'.\n"
echo -e "To get stats, you can use 'sudo nft list ruleset'."
exit 0;

# Wanna delete rule? Replace -A (or -I) with -D and apply!
