#!/bin/bash
# This script will make ur server invisible to ping requests
# But no one can be ping your server
# Execute as sudo!

# Delete previous ICMP rules
iptables -t raw -D PREROUTING -p icmp --icmp-type address-mask-request -j DROP;
iptables -t raw -D PREROUTING -p icmp --icmp-type timestamp-request -j DROP;
iptables -t raw -D PREROUTING -p icmp --icmp-type router-solicitation -j DROP;
iptables -t raw -D PREROUTING -p icmp -m limit --limit 2/second -j ACCEPT

# Just drop all ICMP
iptables -t raw -A PREROUTING -p icmp -j DROP
